version: '3.1'
services:
  client:
    container_name: ai-client-container
    image: ai-client-image
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - server
      - mongo
    links:
      - server
      - mongo
  server:
    container_name: ai-server-container
    image: ai-server-image
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
