"""add column role

Revision ID: a6dfe2d2a965
Revises: 07c71f4389b6
Create Date: 2024-02-11 20:55:31.543919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6dfe2d2a965"
down_revision = "07c71f4389b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_model", sa.Column("role", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_model", "role")
    # ### end Alembic commands ###
