"""add column first_name and last_name

Revision ID: 642e8da38f82
Revises: a6dfe2d2a965
Create Date: 2024-02-11 20:57:51.521402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "642e8da38f82"
down_revision = "a6dfe2d2a965"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_model", sa.Column("first_name", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "user_model", sa.Column("last_name", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_model", "last_name")
    op.drop_column("user_model", "first_name")
    # ### end Alembic commands ###
