"""Your migration message here

Revision ID: af0947999f9e
Revises: 
Create Date: 2024-02-15 22:41:27.284639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af0947999f9e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "interview",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=True),
        sa.Column("description", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=25), nullable=False),
        sa.Column("start_datetime", sa.DateTime(), nullable=False),
        sa.Column("end_datetime", sa.DateTime(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=True),
        sa.Column("hr_user_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hr_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("interview")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
